add_requires("zlib")
    rule("rc")
    set_extensions(".rc")
    before_buildcmd_file(function (target, batchcmds, sourcefile_bin, opt)
        batchcmds:show_progress(opt.progress, "${color.build.object}rule.rc file %s", sourcefile_bin)
        local resultfile = path.filename(sourcefile_bin):gsub(".rc",".res")
        batchcmds:show_progress(opt.progress, "${color.build.object}rule.rc generating %s", resultfile)
        local resultpath = path.join(target:autogendir(),resultfile)
        batchcmds:show_progress(opt.progress, "${color.build.object}rule.rc path for generation %s", resultpath)
        batchcmds:execv("rc.exe","/fo ".. path(resultpath), path(sourcefile_bin))
        batchcmds:add_depfiles(sourcefile_bin)
        batchcmds:set_depmtime(os.mtime(sourcefile_bin))
        local objectfile = target:objectfile(resultpath)
        table.insert(target:objectfiles(), resultpath)
        -- batchcmds:compile(sourcefile_bin, objectfile)
    end)
rule_end()
target("runtime")
    set_kind("binary")
    add_files("src/*/*.cpp")
    set_arch("x86")
    add_includedirs("src","src/game","src/global","src/specific","src/tomb5")
    set_pcheader("src/tomb5/pch.h")
    if(is_mode("debug")) then 
        add_defines("DO_LOG")
    end
    if (is_plat("windows")) then

        add_files("tomb5.rc")
        add_defines("WIN32_LEAN_AND_MEAN")
        add_defines("DIRECTINPUT_VERSION=0x0800")
        add_defines("DIRECT3D_VERSION=0x0700")
        add_defines("_WIN32_WINNT=0x0601")
        add_defines("WINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP")
        add_defines("_WIN32")
        add_defines("_USE_MATH_DEFINES")
        add_syslinks("ole32","d3d9","dxguid","user32","msacm32","gdi32","advapi32","ddraw","dsound","dinput8")
    end
    add_packages("zlib")
target_end()